title: Looped Operation Wiki
description: Wiki for Looped Operation
theme: just-the-docs

url: http://pulsegridstudios.github.io/wiki

aux_links:
  PulseGrid Studios: http://pulsegridstudios.github.io
  
search_enabled: true
color_scheme: dark

logo: "/assets/images/loopedops.png"
favicon_ico: "/assets/images/favicon.ico"
