title: Looped Operations Wiki
description: Official Operations Manual
theme: minima

url: https://pulsegridstudios.github.io
baseurl: /wiki

logo: /assets/images/loopedops.png

aux_links:
  PulseGrid Studios: https://pulsegridstudios.github.io
  Roblox Game: https://www.roblox.com/games/103236484372211/Looped-Operation
  Contributing: https://pulsegridstudios.github.io/contributing/
  
plugins:
  - jekyll-relative-links